name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Build and deploy
        run: >
          uvx
          --with mkdocs-material
          --with mkdocs-git-revision-date-localized-plugin
          mkdocs gh-deploy --force
